# -*- coding: utf-8 -*-
"""review analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xinZm-r1G9o2HyaoyAN3uJcJqev8-sYc
"""

import pandas as pd
import numpy as np
import string
import nltk
import warnings
import joblib

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer, PorterStemmer
from nltk.tokenize import word_tokenize
from string import punctuation

from sklearn.preprocessing import LabelEncoder, MaxAbsScaler,StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.svm import LinearSVC
from sklearn.calibration import CalibratedClassifierCV

from xgboost import XGBClassifier
from scipy.stats import loguniform

warnings.filterwarnings("ignore")

df=pd.read_csv("IMDB Dataset.csv")

df

label=LabelEncoder()
df['sentiment']=label.fit_transform(df['sentiment'])

df.isnull().sum()

df['review'][0]

!pip install nltk

def transform(text):
    text=text.lower()
    text=nltk.word_tokenize(text)
    text=[word for word in text if word.isalnum()]
    text=[word for word in text if word not in stopwords.words('english')]
    text=[WordNetLemmatizer().lemmatize(word) for word in text]
    return " ".join(text)

transform('''One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fac..''')

df['review']=df['review'].apply(transform)

df.to_csv("clean_data.csv", index=False)

# ========== 1. VECTORIZATION ==========
tf = TfidfVectorizer(max_features=3000)
x = tf.fit_transform(df['review']).toarray()
y = df['sentiment'].values

sc = StandardScaler()
x = sc.fit_transform(x)

# ========== 3. TRAIN-TEST SPLIT ==========
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42, stratify=y
)

# ========== 1. VECTORIZATION ==========
tf = TfidfVectorizer(max_features=3000)
x = tf.fit_transform(df['review'])        # ← Keep as sparse matrix (don't use .toarray())
y = df['sentiment'].values

# ========== 2. SCALING ==========
sc = MaxAbsScaler()                       # ← FIXED: MaxAbsScaler works with sparse data
x = sc.fit_transform(x)                   # Sparse matrix preserved

# ========== 3. TRAIN-TEST SPLIT ==========
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42, stratify=y
)

# ========== 4. TRAIN XGBOOST ==========
xgb = XGBClassifier(
    objective='binary:logistic',
    eval_metric='logloss',
    use_label_encoder=False,
    random_state=42
)

xgb.fit(x_train, y_train)

# ========== 5. EVALUATE ==========
y_train_pred = xgb.predict(x_train)
y_test_pred = xgb.predict(x_test)

train_acc = accuracy_score(y_train, y_train_pred)
test_acc = accuracy_score(y_test, y_test_pred)

print(f"Train Accuracy: {train_acc:.4f}")
print(f"Test Accuracy:  {test_acc:.4f}")
print("\n📋 Classification Report:")
print(classification_report(y_test, y_test_pred))
print("\n📊 Confusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))



# ========== 6. PREDICT NEW MOVIE REVIEW ==========
def predict_review(review_text):
    # Transform the new review
    review_tfidf = tf.transform([review_text])    # Returns sparse matrix
    review_scaled = sc.transform(review_tfidf)    # MaxAbsScaler handles sparse

    # Predict
    prediction = xgb.predict(review_scaled)[0]
    probability = xgb.predict_proba(review_scaled)[0]

    sentiment = "Positive" if prediction == 1 else "Negative"
    confidence = probability[prediction]

    return sentiment, confidence

# ========== 7. TEST PREDICTIONS ==========
print("\n" + "=" * 50)
print("🎬 MOVIE REVIEW PREDICTIONS")
print("=" * 50)

reviews = [
    "This movie was absolutely amazing! Best film I've ever seen.",
    "Terrible waste of time. Boring plot and bad acting.",
    "The cinematography was stunning but the story was weak.",
    "A masterpiece! Brilliant performances and gripping storyline.",
    "I fell asleep halfway through. Completely dull and predictable."
]

for review in reviews:
    sentiment, confidence = predict_review(review)
    emoji = "😊" if sentiment == "Positive" else "😞"
    print(f"\n{emoji} Review: '{review}'")
    print(f"   Sentiment: {sentiment}")
    print(f"   Confidence: {confidence:.2%}")

reviews = ['''
not intrested
'''
]

for review in reviews:
    sentiment, confidence = predict_review(review)
    emoji = "😊" if sentiment == "Positive" else "😞"
    print(f"\n{emoji} Review: '{review}'")
    print(f"   Sentiment: {sentiment}")
    print(f"   Confidence: {confidence:.2%}")

from sklearn.svm import LinearSVC

# LinearSVC is faster than SVC for high-dimensional text data
model = LinearSVC(C=1.0, max_iter=2000, random_state=42)
model.fit(x_train, y_train)

# For probability output (optional)
from sklearn.calibration import CalibratedClassifierCV
model = CalibratedClassifierCV(LinearSVC(C=1.0, max_iter=2000), cv=3)
model.fit(x_train, y_train)
print(accuracy_score(y_test, model.predict(x_test)))
print(confusion_matrix(y_test, model.predict(x_test)))

from sklearn.naive_bayes import MultinomialNB

# ⚠️ Don't use MaxAbsScaler with Naive Bayes! Use raw TF-IDF or CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer

tf = CountVectorizer(max_features=3000)
x = tf.fit_transform(df['review'])  # Keep sparse, no scaling needed

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42, stratify=y)

model = MultinomialNB(alpha=1.0)
model.fit(x_train, y_train)
print(accuracy_score(y_test, model.predict(x_test)))
print(confusion_matrix(y_test, model.predict(x_test)))

# Base model
base_svc = LinearSVC(random_state=42, max_iter=5000)

# Parameter distribution (random sampling)
param_dist = {
    'estimator__C': loguniform(0.01, 100),        # Random log-scale values
    'estimator__loss': ['hinge', 'squared_hinge'],
    'estimator__class_weight': [None, 'balanced'],
    'cv': [3, 5]                                  # Random CV folds
}

# Calibrated wrapper for probability output
calibrated_svc = CalibratedClassifierCV(base_svc, method='sigmoid')

# RandomizedSearchCV - FAST! Only tests 10 random combinations
random_search = RandomizedSearchCV(
    calibrated_svc,
    param_distributions={
        'estimator__C': loguniform(0.01, 100),
        'estimator__loss': ['hinge', 'squared_hinge'],
        'estimator__class_weight': [None, 'balanced']
    },
    n_iter=10,              # Only 10 random combos (vs hundreds in GridSearch)
    cv=3,                   # 3-fold CV
    scoring='accuracy',
    n_jobs=-1,              # Use all CPU cores
    random_state=42,
    verbose=1
)

# Fit
random_search.fit(x_train, y_train)

# ========== 3. RESULTS ==========
print("=" * 50)
print("⚡ FAST TUNING RESULTS")
print("=" * 50)
print(f"Best Params: {random_search.best_params_}")
print(f"Best CV Score: {random_search.best_score_:.4f}")

best_model = random_search.best_estimator_

# ========== 4. EVALUATE ==========
y_pred = best_model.predict(x_test)

print(f"\nTest Accuracy: {accuracy_score(y_test, y_pred):.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# ========== 5. SAVE ==========
joblib.dump(best_model, 'linearsvc_tuned_model.pkl')
joblib.dump(tf, 'tfidf_vectorizer.pkl')
joblib.dump(sc, 'scaler.pkl')
print("\n✅ Model saved!")

# ========== 6. PREDICT NEW REVIEW ==========
def predict_review(text):
    review_tfidf = tf.transform([text])
    review_scaled = sc.transform(review_tfidf)
    pred = best_model.predict(review_scaled)[0]
    prob = best_model.predict_proba(review_scaled)[0]
    sentiment = "Positive" if pred == 1 else "Negative"
    return sentiment, prob[pred]

# Test
reviews = [
    "Amazing movie! Best I've ever seen.",
    "Terrible waste of time. So boring."
]

for r in reviews:
    sent, conf = predict_review(r)
    print(f"\n'{r}' → {sent} ({conf:.2%})")

def predict_review(text):
    review_tfidf = tf.transform([text])
    review_scaled = sc.transform(review_tfidf)
    pred = best_model.predict(review_scaled)[0]
    prob = best_model.predict_proba(review_scaled)[0]
    sentiment = "Positive" if pred == 1 else "Negative"
    return sentiment, prob[pred]

# Test
reviews = ['''
 bad
'''

]

for r in reviews:
    sent, conf = predict_review(r)
    print(f"\n'{r}' → {sent} ({conf:.2%})")

